In [1]:
import cv2
import numpy as np
from PIL import Image
import pandas
import math

def RelativePose(pose1, pose2):
    c = np.cos(-pose1[2])
    s = np.sin(-pose1[2])
    x = pose2[0] - pose1[0]
    y = pose2[1] - pose1[1]
    Theta = pose2[2] - pose1[2]
    X = c*x - s*y
    Y = s*x + c*y
    return np.array([X, Y, Theta])

def GenerateInputVector(dir):
    max_succ_dist = 0.5
    max_succ_ang = math.radians(10)
    pose_list = pandas.read_csv(dir + 'pose_list.csv', header=None).values
    N = len(pose_list)
    
    image1_list = []
    image2_list = []
    rel_pose_list = []
    for i in range(0, N-1):
        for j in range(i+1, N, 1):
            rel_pose = RelativePose(pose_list[i], pose_list[j])
            dist = np.sqrt(rel_pose[0]*rel_pose[0] + rel_pose[1]*rel_pose[1])
            ang = rel_pose[2]
            if dist < max_succ_dist and ang < max_succ_ang:
                print(str(i)+','+str(j))
                image1_list.append(cv2.imread(dir + 'img_' + str(i) + '.jpg', 0)/255)
                image2_list.append(cv2.imread(dir + 'img_' + str(j) + '.jpg', 0)/255)
                rel_pose_list.append(rel_pose)
    return image1_list, image2_list, rel_pose_list

In [3]:
dir = '/home/rj/Downloads/scan-matching-cnn-main/data/traj_2/'
image1_list, image2_list, rel_pose_list = GenerateInputVector(dir)

0,1
0,2
0,3
0,4
0,5
0,6
0,7
0,8
0,9
0,10
0,11
0,12
0,13
0,14
0,15
0,16
0,17
0,18
0,19
0,20
0,21
0,22
0,23
0,24
1,2
1,3
1,4
1,5
1,6
1,7
1,8
1,9
1,10
1,11
1,12
1,13
1,14
1,15
1,16
1,17
1,18
1,19
1,20
1,21
1,22
1,23
1,24
2,3
2,4
2,5
2,6
2,7
2,8
2,9
2,10
2,11
2,12
2,13
2,14
2,15
2,16
2,17
2,18
2,19
2,20
2,21
2,22
2,23
2,24
2,25
3,4
3,5
3,6
3,7
3,8
3,9
3,10
3,11
3,12
3,13
3,14
3,15
3,16
3,17
3,18
3,19
3,20
3,21
3,22
3,23
3,24
3,25
4,5
4,6
4,7
4,8
4,9
4,10
4,11
4,12
4,13
4,14
4,15
4,16
4,17
4,18
4,19
4,20
4,21
4,22
4,23
4,24
4,25
4,26
5,6
5,7
5,8
5,9
5,10
5,11
5,12
5,13
5,14
5,15
5,16
5,17
5,18
5,19
5,20
5,21
5,22
5,23
5,24
5,25
5,26
5,27
6,7
6,8
6,9
6,10
6,11
6,12
6,13
6,14
6,15
6,16
6,17
6,18
6,19
6,20
6,21
6,22
6,23
6,24
6,25
6,26
6,27
6,28
7,8
7,9
7,10
7,11
7,12
7,13
7,14
7,15
7,16
7,17
7,18
7,19
7,20
7,21
7,22
7,23
7,24
7,25
7,26
7,27
7,28
7,29
8,9
8,10
8,11
8,12
8,13
8,14
8,15
8,16
8,17
8,18
8,19
8,20
8,21
8,22
8,23
8,24
8,25
8,26
8,27
8,28
8,29
8,30
9,10
9,11
9,12
9,13
9,14
9,15
9,16


67,81
67,82
67,83
67,84
67,85
67,86
67,87
67,88
67,89
67,90
68,69
68,70
68,71
68,72
68,73
68,74
68,75
68,76
68,77
68,78
68,79
68,80
68,81
68,82
68,83
68,84
68,85
68,86
68,87
68,88
68,89
68,90
68,91
69,70
69,71
69,72
69,73
69,74
69,75
69,76
69,77
69,78
69,79
69,80
69,81
69,82
69,83
69,84
69,85
69,86
69,87
69,88
69,89
69,90
69,91
69,92
70,71
70,72
70,73
70,74
70,75
70,76
70,77
70,78
70,79
70,80
70,81
70,82
70,83
70,84
70,85
70,86
70,87
70,88
70,89
70,90
70,91
70,92
70,93
71,72
71,73
71,74
71,75
71,76
71,77
71,78
71,79
71,80
71,81
71,82
71,83
71,84
71,85
71,86
71,87
71,88
71,89
71,90
71,91
71,92
71,93
71,94
72,73
72,74
72,75
72,76
72,77
72,78
72,79
72,80
72,81
72,82
72,83
72,84
72,85
72,86
72,87
72,88
72,89
72,90
72,91
72,92
72,93
72,94
72,95
73,74
73,75
73,76
73,77
73,78
73,79
73,80
73,81
73,82
73,83
73,84
73,85
73,86
73,87
73,88
73,89
73,90
73,91
73,92
73,93
73,94
73,95
74,75
74,76
74,77
74,78
74,79
74,80
74,81
74,82
74,83
74,84
74,85
74,86
74,87
74,88
74,89
74,90
74,91
74,92
74,93
74,9

125,126
125,127
125,128
125,129
125,130
125,131
125,132
125,133
125,134
125,135
125,136
125,137
125,138
125,139
125,140
125,141
125,142
125,143
125,144
125,145
125,146
125,147
125,148
125,149
126,127
126,128
126,129
126,130
126,131
126,132
126,133
126,134
126,135
126,136
126,137
126,138
126,139
126,140
126,141
126,142
126,143
126,144
126,145
126,146
126,147
126,148
126,149
126,150
127,128
127,129
127,130
127,131
127,132
127,133
127,134
127,135
127,136
127,137
127,138
127,139
127,140
127,141
127,142
127,143
127,144
127,145
127,146
127,147
127,148
127,149
127,150
127,151
128,129
128,130
128,131
128,132
128,133
128,134
128,135
128,136
128,137
128,138
128,139
128,140
128,141
128,142
128,143
128,144
128,145
128,146
128,147
128,148
128,149
128,150
128,151
128,152
129,130
129,131
129,132
129,133
129,134
129,135
129,136
129,137
129,138
129,139
129,140
129,141
129,142
129,143
129,144
129,145
129,146
129,147
129,148
129,149
129,150
129,151
129,152
129,153
130,131
130,132
130,133
130,134
130,135


171,175
171,176
171,177
171,178
171,179
171,180
171,181
171,182
171,183
171,184
171,185
171,186
171,187
171,188
171,189
171,190
171,191
171,192
171,193
171,194
171,195
172,173
172,174
172,175
172,176
172,177
172,178
172,179
172,180
172,181
172,182
172,183
172,184
172,185
172,186
172,187
172,188
172,189
172,190
172,191
172,192
172,193
172,194
172,195
172,196
173,174
173,175
173,176
173,177
173,178
173,179
173,180
173,181
173,182
173,183
173,184
173,185
173,186
173,187
173,188
173,189
173,190
173,191
173,192
173,193
173,194
173,195
173,196
173,197
174,175
174,176
174,177
174,178
174,179
174,180
174,181
174,182
174,183
174,184
174,185
174,186
174,187
174,188
174,189
174,190
174,191
174,192
174,193
174,194
174,195
174,196
174,197
174,198
175,176
175,177
175,178
175,179
175,180
175,181
175,182
175,183
175,184
175,185
175,186
175,187
175,188
175,189
175,190
175,191
175,192
175,193
175,194
175,195
175,196
175,197
175,198
175,199
176,177
176,178
176,179
176,180
176,181
176,182
176,183
176,184


217,238
217,239
217,240
217,241
218,219
218,220
218,221
218,222
218,223
218,224
218,225
218,226
218,227
218,228
218,229
218,230
218,231
218,232
218,233
218,234
218,235
218,236
218,237
218,238
218,239
218,240
218,241
218,242
219,220
219,221
219,222
219,223
219,224
219,225
219,226
219,227
219,228
219,229
219,230
219,231
219,232
219,233
219,234
219,235
219,236
219,237
219,238
219,239
219,240
219,241
219,242
219,243
220,221
220,222
220,223
220,224
220,225
220,226
220,227
220,228
220,229
220,230
220,231
220,232
220,233
220,234
220,235
220,236
220,237
220,238
220,239
220,240
220,241
220,242
220,243
220,244
221,222
221,223
221,224
221,225
221,226
221,227
221,228
221,229
221,230
221,231
221,232
221,233
221,234
221,235
221,236
221,237
221,238
221,239
221,240
221,241
221,242
221,243
221,244
221,245
222,223
222,224
222,225
222,226
222,227
222,228
222,229
222,230
222,231
222,232
222,233
222,234
222,235
222,236
222,237
222,238
222,239
222,240
222,241
222,242
222,243
222,244
222,245
222,246
223,224


264,277
264,278
264,279
264,280
264,281
264,282
264,283
264,284
264,285
264,286
264,287
264,288
265,266
265,267
265,268
265,269
265,270
265,271
265,272
265,273
265,274
265,275
265,276
265,277
265,278
265,279
265,280
265,281
265,282
265,283
265,284
265,285
265,286
265,287
265,288
265,289
266,267
266,268
266,269
266,270
266,271
266,272
266,273
266,274
266,275
266,276
266,277
266,278
266,279
266,280
266,281
266,282
266,283
266,284
266,285
266,286
266,287
266,288
266,289
266,290
267,268
267,269
267,270
267,271
267,272
267,273
267,274
267,275
267,276
267,277
267,278
267,279
267,280
267,281
267,282
267,283
267,284
267,285
267,286
267,287
267,288
267,289
267,290
267,291
268,269
268,270
268,271
268,272
268,273
268,274
268,275
268,276
268,277
268,278
268,279
268,280
268,281
268,282
268,283
268,284
268,285
268,286
268,287
268,288
268,289
268,290
268,291
268,292
269,270
269,271
269,272
269,273
269,274
269,275
269,276
269,277
269,278
269,279
269,280
269,281
269,282
269,283
269,284
269,285
269,286


313,319
313,320
313,321
313,322
313,323
313,324
313,325
313,326
313,327
313,328
313,329
313,330
313,331
313,332
313,333
313,334
313,335
313,336
313,337
314,315
314,316
314,317
314,318
314,319
314,320
314,321
314,322
314,323
314,324
314,325
314,326
314,327
314,328
314,329
314,330
314,331
314,332
314,333
314,334
314,335
314,336
314,337
314,338
315,316
315,317
315,318
315,319
315,320
315,321
315,322
315,323
315,324
315,325
315,326
315,327
315,328
315,329
315,330
315,331
315,332
315,333
315,334
315,335
315,336
315,337
315,338
315,339
315,340
316,317
316,318
316,319
316,320
316,321
316,322
316,323
316,324
316,325
316,326
316,327
316,328
316,329
316,330
316,331
316,332
316,333
316,334
316,335
316,336
316,337
316,338
316,339
316,340
316,341
317,318
317,319
317,320
317,321
317,322
317,323
317,324
317,325
317,326
317,327
317,328
317,329
317,330
317,331
317,332
317,333
317,334
317,335
317,336
317,337
317,338
317,339
317,340
317,341
317,342
318,319
318,320
318,321
318,322
318,323
318,324
318,325


362,377
362,378
362,379
362,380
362,381
362,382
362,383
362,384
362,385
362,386
362,387
363,364
363,365
363,366
363,367
363,368
363,369
363,370
363,371
363,372
363,373
363,374
363,375
363,376
363,377
363,378
363,379
363,380
363,381
363,382
363,383
363,384
363,385
363,386
363,387
363,388
364,365
364,366
364,367
364,368
364,369
364,370
364,371
364,372
364,373
364,374
364,375
364,376
364,377
364,378
364,379
364,380
364,381
364,382
364,383
364,384
364,385
364,386
364,387
364,388
364,389
365,366
365,367
365,368
365,369
365,370
365,371
365,372
365,373
365,374
365,375
365,376
365,377
365,378
365,379
365,380
365,381
365,382
365,383
365,384
365,385
365,386
365,387
365,388
365,389
365,390
366,367
366,368
366,369
366,370
366,371
366,372
366,373
366,374
366,375
366,376
366,377
366,378
366,379
366,380
366,381
366,382
366,383
366,384
366,385
366,386
366,387
366,388
366,389
366,390
366,391
367,368
367,369
367,370
367,371
367,372
367,373
367,374
367,375
367,376
367,377
367,378
367,379
367,380
367,381


405,406
405,407
405,408
405,409
405,410
405,411
405,412
405,413
405,414
405,415
405,416
405,417
405,418
405,419
405,420
405,421
405,422
405,423
405,424
405,425
405,426
405,427
405,428
405,429
405,430
406,407
406,408
406,409
406,410
406,411
406,412
406,413
406,414
406,415
406,416
406,417
406,418
406,419
406,420
406,421
406,422
406,423
406,424
406,425
406,426
406,427
406,428
406,429
406,430
406,431
407,408
407,409
407,410
407,411
407,412
407,413
407,414
407,415
407,416
407,417
407,418
407,419
407,420
407,421
407,422
407,423
407,424
407,425
407,426
407,427
407,428
407,429
407,430
407,431
407,432
408,409
408,410
408,411
408,412
408,413
408,414
408,415
408,416
408,417
408,418
408,419
408,420
408,421
408,422
408,423
408,424
408,425
408,426
408,427
408,428
408,429
408,430
408,431
408,432
408,433
409,410
409,411
409,412
409,413
409,414
409,415
409,416
409,417
409,418
409,419
409,420
409,421
409,422
409,423
409,424
409,425
409,426
409,427
409,428
409,429
409,430
409,431
409,432
409,433
409,434


446,463
446,464
446,465
446,466
446,467
446,468
446,469
446,470
446,471
447,448
447,449
447,450
447,451
447,452
447,453
447,454
447,455
447,456
447,457
447,458
447,459
447,460
447,461
447,462
447,463
447,464
447,465
447,466
447,467
447,468
447,469
447,470
447,471
448,449
448,450
448,451
448,452
448,453
448,454
448,455
448,456
448,457
448,458
448,459
448,460
448,461
448,462
448,463
448,464
448,465
448,466
448,467
448,468
448,469
448,470
448,471
448,472
448,473
449,450
449,451
449,452
449,453
449,454
449,455
449,456
449,457
449,458
449,459
449,460
449,461
449,462
449,463
449,464
449,465
449,466
449,467
449,468
449,469
449,470
449,471
449,472
449,473
449,474
450,451
450,452
450,453
450,454
450,455
450,456
450,457
450,458
450,459
450,460
450,461
450,462
450,463
450,464
450,465
450,466
450,467
450,468
450,469
450,470
450,471
450,472
450,473
450,474
450,475
451,452
451,453
451,454
451,455
451,456
451,457
451,458
451,459
451,460
451,461
451,462
451,463
451,464
451,465
451,466
451,467
451,468


491,498
491,499
491,500
491,501
491,502
491,503
491,504
491,505
491,506
491,507
491,508
491,509
491,510
491,511
491,512
491,513
491,514
491,515
491,516
492,493
492,494
492,495
492,496
492,497
492,498
492,499
492,500
492,501
492,502
492,503
492,504
492,505
492,506
492,507
492,508
492,509
492,510
492,511
492,512
492,513
492,514
492,515
492,516
492,517
493,494
493,495
493,496
493,497
493,498
493,499
493,500
493,501
493,502
493,503
493,504
493,505
493,506
493,507
493,508
493,509
493,510
493,511
493,512
493,513
493,514
493,515
493,516
493,517
493,518
494,495
494,496
494,497
494,498
494,499
494,500
494,501
494,502
494,503
494,504
494,505
494,506
494,507
494,508
494,509
494,510
494,511
494,512
494,513
494,514
494,515
494,516
494,517
494,518
494,519
495,496
495,497
495,498
495,499
495,500
495,501
495,502
495,503
495,504
495,505
495,506
495,507
495,508
495,509
495,510
495,511
495,512
495,513
495,514
495,515
495,516
495,517
495,518
495,519
496,497
496,498
496,499
496,500
496,501
496,502
496,503


534,556
534,557
534,558
535,536
535,537
535,538
535,539
535,540
535,541
535,542
535,543
535,544
535,545
535,546
535,547
535,548
535,549
535,550
535,551
535,552
535,553
535,554
535,555
535,556
535,557
535,558
535,559
535,560
536,537
536,538
536,539
536,540
536,541
536,542
536,543
536,544
536,545
536,546
536,547
536,548
536,549
536,550
536,551
536,552
536,553
536,554
536,555
536,556
536,557
536,558
536,559
536,560
537,538
537,539
537,540
537,541
537,542
537,543
537,544
537,545
537,546
537,547
537,548
537,549
537,550
537,551
537,552
537,553
537,554
537,555
537,556
537,557
537,558
537,559
537,560
537,561
537,562
538,539
538,540
538,541
538,542
538,543
538,544
538,545
538,546
538,547
538,548
538,549
538,550
538,551
538,552
538,553
538,554
538,555
538,556
538,557
538,558
538,559
538,560
538,561
538,562
538,563
539,540
539,541
539,542
539,543
539,544
539,545
539,546
539,547
539,548
539,549
539,550
539,551
539,552
539,553
539,554
539,555
539,556
539,557
539,558
539,559
539,560
539,561
539,562


In [7]:
rel_pose_list #x in meter, y, theta in radians

[array([0., 0., 0.]),
 array([0.0094    , 0.        , 0.00043721]),
 array([ 2.87000e-02, -1.00000e-05, -1.01331e-03]),
 array([ 4.87000e-02, -5.00000e-05, -3.70064e-03]),
 array([ 0.0688    , -0.00014   , -0.00605629]),
 array([ 0.0888   , -0.00027  , -0.0069049]),
 array([ 0.1088    , -0.00042   , -0.00871841]),
 array([ 0.1288    , -0.0006    , -0.00906016]),
 array([ 0.1588   , -0.00092  , -0.0113989]),
 array([ 0.1788   , -0.00117  , -0.0130055]),
 array([ 0.1987   , -0.00142  , -0.0135325]),
 array([ 0.2187  , -0.00168 , -0.010142]),
 array([ 0.2387   , -0.00188  , -0.0102746]),
 array([ 0.2687    , -0.00213   , -0.00653403]),
 array([ 0.2887    , -0.00225   , -0.00397965]),
 array([ 0.3087   , -0.00232  , -0.0031593]),
 array([ 0.3287    , -0.00238   , -0.00298208]),
 array([ 0.3487   , -0.00243  , -0.0024322]),
 array([ 0.3687    , -0.00246   , -0.00086306]),
 array([ 0.3887   , -0.00246  ,  0.0014371]),
 array([ 0.4187    , -0.00241   ,  0.00202726]),
 array([ 0.4387    , -0.0

In [46]:
import torch
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):
    #Architecture is LeNet modification
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(2, 6, 5).cuda()
        self.conv2 = nn.Conv2d(6, 16, 5).cuda()
        self.fc1 = nn.Linear(44944, 120).cuda()
        self.fc2 = nn.Linear(120, 84).cuda()
        self.fc3 = nn.Linear(84, 1).cuda()

    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        #print(x.shape)
        x = torch.flatten(x, 1
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x


net = Net()
print(net)

Net(
  (conv1): Conv2d(2, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=44944, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=1, bias=True)
)


In [17]:
input = torch.randn(1, 2, 224, 224)
out = net(input)
print(out)

torch.Size([1, 16, 53, 53])
tensor([[0.0087]], grad_fn=<AddmmBackward>)


In [26]:
x = np.stack([image1_list[0], image2_list[0]])
x = np.expand_dims(x, axis=0)
x.shape

(1, 2, 224, 224)

In [70]:
import random
import torch.optim as optim
idxs = list(range(len(image1_list)))
#random.shuffle(idxs)
net_x = Net()
optimizer = optim.Adam(net_x.parameters(), lr=0.0001)
train_idxs = idxs[:int(len(image1_list) * 0.8)]
test_idxs = idxs[int(len(image1_list) * 0.8):]
min_loss = 1
for epoch in range(10):
    train_total = 0
    test_total = 0
    for idx in test_idxs:
        x = np.stack([image1_list[idx], image2_list[idx]])
        x = torch.tensor(np.expand_dims(x, axis=0)).float().cuda()
        out = net_x(x)
        target = torch.tensor(rel_pose_list[idx][0]).float().cuda()
        criterion = nn.MSELoss()
        loss = criterion(out, target)
        test_total += loss.item()
    print("Test loss:", test_total / len(test_idxs))
    if min_loss > test_total / len(test_idxs):
        print("New lowest test loss, saved!")
        torch.save(net_x, "net_x.pyt")
        min_loss = test_total / len(test_idxs)
    optimizer.zero_grad()
    for idx in train_idxs:
        x = np.stack([image1_list[idx], image2_list[idx]])
        x = torch.tensor(np.expand_dims(x, axis=0)).float().cuda()
        out = net_x(x)
        target = torch.tensor(rel_pose_list[idx][0]).float().cuda()
        criterion = nn.MSELoss()
        loss = criterion(out, target)
        loss.backward()
        train_total += loss.item()
    optimizer.step()     
    print("Train loss:", train_total / len(train_idxs))


Test loss: 0.09316273704033466
New lowest test loss, saved!
Train loss: 0.09760601105996577
Test loss: 0.08120835832970595
New lowest test loss, saved!
Train loss: 0.08237792620783592
Test loss: 0.0709988091326192
New lowest test loss, saved!
Train loss: 0.07041106703584246
Test loss: 0.06171326743327536
New lowest test loss, saved!
Train loss: 0.059603465614162916
Test loss: 0.0532042132760322
New lowest test loss, saved!
Train loss: 0.04943579472305147
Test loss: 0.04484777223532211
New lowest test loss, saved!
Train loss: 0.039938934377519816
Test loss: 0.037062504074123294
New lowest test loss, saved!
Train loss: 0.031580642478625624
Test loss: 0.030203012489329547
New lowest test loss, saved!
Train loss: 0.024909945874083746
Test loss: 0.024936106662160236
New lowest test loss, saved!
Train loss: 0.02079067325832627
Test loss: 0.02184576651259127
New lowest test loss, saved!
Train loss: 0.019840016093320957


In [73]:
import random
import torch.optim as optim
idxs = list(range(len(image1_list)))
random.shuffle(idxs)
net_y = Net()
optimizer = optim.Adam(net_y.parameters(), lr=0.0001)
train_idxs = idxs[:int(len(image1_list) * 0.8)]
test_idxs = idxs[int(len(image1_list) * 0.8):]
min_loss = 1
for epoch in range(10):
    train_total = 0
    test_total = 0
    for idx in test_idxs:
        x = np.stack([image1_list[idx], image2_list[idx]])
        x = torch.tensor(np.expand_dims(x, axis=0)).float().cuda()
        out = net_y(x)
        target = torch.tensor(rel_pose_list[idx][1]).float().cuda()
        criterion = nn.MSELoss()
        loss = criterion(out, target)
        test_total += loss.item()
    print("Test loss:", test_total / len(test_idxs))
    if min_loss > test_total / len(test_idxs):
        print("New lowest test loss, saved!")
        torch.save(net_y, "net_y.pyt")
        min_loss = test_total / len(test_idxs)
    optimizer.zero_grad()
    for idx in train_idxs:
        x = np.stack([image1_list[idx], image2_list[idx]])
        x = torch.tensor(np.expand_dims(x, axis=0)).float().cuda()
        out = net_y(x)
        target = torch.tensor(rel_pose_list[idx][1]).float().cuda()
        criterion = nn.MSELoss()
        loss = criterion(out, target)
        loss.backward()
        train_total += loss.item()
    optimizer.step()     
    print("Train loss:", train_total / len(train_idxs))


Test loss: 9.617286789466956e-05
New lowest test loss, saved!
Train loss: 9.564128475229344e-05
Test loss: 0.011646892958916697
Train loss: 0.011643050268307828
Test loss: 0.00031271440784711655
Train loss: 0.0003174171151200748
Test loss: 0.0010157343196309009
Train loss: 0.0010063049519127838
Test loss: 0.001289476347003614
Train loss: 0.0012784373348956987
Test loss: 0.00101932288761833
Train loss: 0.0010106096948527157
Test loss: 0.0005646956199061599
Train loss: 0.0005595948882627724
Test loss: 0.00023482042197335554
Train loss: 0.00023266005458126332
Test loss: 7.849430022468777e-05
New lowest test loss, saved!
Train loss: 7.841103920871232e-05
Test loss: 7.615335217875473e-05
New lowest test loss, saved!
Train loss: 7.766152776563352e-05


In [74]:
import random
import torch.optim as optim
idxs = list(range(len(image1_list)))
random.shuffle(idxs)
net_angle = Net()
optimizer = optim.Adam(net_angle.parameters(), lr=0.0001)
train_idxs = idxs[:int(len(image1_list) * 0.8)]
test_idxs = idxs[int(len(image1_list) * 0.8):]
min_loss = 1
for epoch in range(10):
    train_total = 0
    test_total = 0
    for idx in test_idxs:
        x = np.stack([image1_list[idx], image2_list[idx]])
        x = torch.tensor(np.expand_dims(x, axis=0)).float().cuda()
        out = net_angle(x)
        target = torch.tensor(rel_pose_list[idx][2]).float().cuda()
        criterion = nn.MSELoss()
        loss = criterion(out, target)
        test_total += loss.item()
    print("Test loss:", test_total / len(test_idxs))
    if min_loss > test_total / len(test_idxs):
        print("New lowest test loss, saved!")
        torch.save(net_angle, "net_angle.pyt")
        min_loss = test_total / len(test_idxs)
    optimizer.zero_grad()
    for idx in train_idxs:
        x = np.stack([image1_list[idx], image2_list[idx]])
        x = torch.tensor(np.expand_dims(x, axis=0)).float().cuda()
        out = net_angle(x)
        target = torch.tensor(rel_pose_list[idx][2]).float().cuda()
        criterion = nn.MSELoss()
        loss = criterion(out, target)
        loss.backward()
        train_total += loss.item()
    optimizer.step()     
    print("Train loss:", train_total / len(train_idxs))


Test loss: 0.0012304176175288557
New lowest test loss, saved!
Train loss: 0.0012780109660109765
Test loss: 0.0015036335300443427
Train loss: 0.0015400194865430286
Test loss: 0.0008204401604200331
New lowest test loss, saved!
Train loss: 0.0008586553314057506
Test loss: 0.0009636337091800085
Train loss: 0.0009976001209504382
Test loss: 0.0007884225624985192
New lowest test loss, saved!
Train loss: 0.000817238797188232
Test loss: 0.0006006804592383184
New lowest test loss, saved!
Train loss: 0.000626546435784615
Test loss: 0.0006011972769357974
Train loss: 0.0006257686370488502
Test loss: 0.0006474863397134353
Train loss: 0.0006709386721407664
Test loss: 0.0006254802024199827
Train loss: 0.0006481165075189884
Test loss: 0.000570218194167849
New lowest test loss, saved!
Train loss: 0.0005912083507668782
